c_data <- read.csv(file="household_power_consumption.txt", header = TRUE, sep = ";", stringsAsFactors = FALSE)
c_data <- transform(c_data, Date = as.Date(Date,"%d/%m/%Y"))
f_data <- subset(c_data, Date >= "2007-02-01" & Date <= "2007-02-02")
f_data <- transform(f_data,Global_active_power = as.numeric(Global_active_power))
f_data <- transform(f_data,Sub_metering_1 = as.numeric(Sub_metering_1), Sub_metering_2 = as.numeric(Sub_metering_2), Sub_metering_3 = as.numeric(Sub_metering_3))
f_data <- transform(f_data, Voltage = as.numeric(Voltage) , Global_reactive_power = as.numeric(Global_reactive_power))
par(mfrow = c(2,2),mar= c(3.9,3.9,1,1)  , oma = c(0,0,0,0), cex.lab = 0.85)
plot(as.POSIXct(paste(f_data$Date, f_data$Time), format="%Y-%m-%d %H:%M:%S"), f_data$Global_active_power, type = "l", ylab="Global Active Power" , xlab ="")
plot(as.POSIXct(paste(f_data$Date, f_data$Time), format="%Y-%m-%d %H:%M:%S"), f_data$Voltage, type = "l", ylab="Voltage" , xlab ="datetime", yaxt = "n")
plot(as.POSIXct(paste(f_data$Date, f_data$Time), format="%Y-%m-%d %H:%M:%S"), f_data$Sub_metering_1, type = "l", ylab="Energy sub metering", xlab="")
points(as.POSIXct(paste(f_data$Date, f_data$Time), format="%Y-%m-%d %H:%M:%S"), f_data$Sub_metering_2, type = "l", col = "Red")
points(as.POSIXct(paste(f_data$Date, f_data$Time), format="%Y-%m-%d %H:%M:%S"), f_data$Sub_metering_3, type = "l", col = "Blue")
legend("topright", legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col = c("black","red","blue") , lty = c(1,1,1), bty="n", cex=0.5)
plot(as.POSIXct(paste(f_data$Date, f_data$Time), format="%Y-%m-%d %H:%M:%S"), f_data$Global_reactive_power, type = "l", ylab="Global Reactive Power" , xlab ="datetime")
dev.copy(png, file="plot4.png", width = 480 , height = 480 , units = "px")
dev.off(which = dev.cur())